USE lab3;
GO

--SOLUTION: set transaction isolation level to read commited
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM ANIMAL
WAITFOR DELAY '00:00:06'
SELECT * FROM ANIMAL
COMMIT TRAN