USE lab3
GO

INSERT INTO ANIMAL VALUES(60, 'Lowi', 'Dog', 5)
ALTER DATABASE lab3 SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE ANIMAL SET name = 'New Name 1' WHERE aid = 60
WAITFOR DELAY '00:00:05'
COMMIT TRAN

